version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orderdb:
    container_name: orderdb
    restart: always
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=admin1234
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=sid@tamu.edu
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
    # volumes:
    #   - ~/.aspnet/https:/root/.aspnet/https:ro
    #   - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8001:80"
    depends_on:
      - basketdb
      - rabbitmq
    # volumes:
    #   - ~/.aspnet/https:/root/.aspnet/https:ro
    #   - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=Host=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=admin1234"

    ports:
      - "8002:80"
    depends_on:
      - discountdb
    #volumes:
    #  - ~/.aspnet/https:/root/.aspnet/https:ro
    #  - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  discount.grpc:
    container_name: discount.grpc
    environment:
      - "DatabaseSettings:ConnectionString=Host=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=admin1234"
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=True;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"
      # volumes:
      # - ~/.aspnet/https:/root/.aspnet/https:ro
      # - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8010:80"
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - discount.grpc
      - ordering.api
    # volumes:
    #   - ~/.aspnet/https:/root/.aspnet/https:ro
    #   - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  shopping.aggregator:
    container_name: shopping.aggregator
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:DiscountUrl=http://discount.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    ports:
      - "8005:80"
